2024-10-28 22:41:48 INFO Starting test suite tests.common.test_data_explorer
2024-10-28 22:41:48 DEBUG Starting new HTTPS connection (1): pypi.org:443
2024-10-28 22:41:49 DEBUG https://pypi.org:443 "GET /pypi/vnstock3/json HTTP/1.1" 200 9152
2024-10-28 22:41:49 DEBUG matplotlib data path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/mpl-data
2024-10-28 22:41:49 DEBUG CONFIGDIR=/Users/mrthinh/.matplotlib
2024-10-28 22:41:49 DEBUG interactive is False
2024-10-28 22:41:49 DEBUG platform is darwin
2024-10-28 22:41:49 DEBUG CACHEDIR=/Users/mrthinh/.matplotlib
2024-10-28 22:41:49 DEBUG Using fontManager instance from /Users/mrthinh/.matplotlib/fontlist-v330.json
2024-10-28 22:41:50 DEBUG Starting new HTTPS connection (1): assets.msn.com:443
2024-10-28 22:41:50 DEBUG https://assets.msn.com:443 "GET /resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.130&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20 HTTP/1.1" 200 None
2024-10-28 22:41:50 DEBUG Starting new HTTPS connection (1): assets.msn.com:443
2024-10-28 22:41:50 DEBUG https://assets.msn.com:443 "GET /resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.130&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20 HTTP/1.1" 200 770783
2024-10-28 22:41:50 DEBUG Starting new HTTPS connection (1): api.vietcap.com.vn:443
2024-10-28 22:41:50 DEBUG https://api.vietcap.com.vn:443 "POST /data-mt/graphql HTTP/1.1" 200 54216
2024-10-28 22:41:50 WARNING Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
2024-10-28 22:41:50 WARNING Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
2024-10-28 22:41:50 WARNING Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
2024-10-28 22:41:50 DEBUG Starting new HTTPS connection (1): api.vietcap.com.vn:443
2024-10-28 22:41:50 DEBUG https://api.vietcap.com.vn:443 "POST /data-mt/graphql HTTP/1.1" 200 54216
2024-10-28 22:41:50 WARNING Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
2024-10-28 22:41:50 DEBUG Starting new HTTPS connection (1): api.vietcap.com.vn:443
2024-10-28 22:41:50 DEBUG https://api.vietcap.com.vn:443 "POST /data-mt/graphql HTTP/1.1" 200 54216
2024-10-28 22:41:50 WARNING Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
2024-10-28 22:41:50 DEBUG Starting new HTTPS connection (1): assets.msn.com:443
2024-10-28 22:41:51 DEBUG https://assets.msn.com:443 "GET /resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.130&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20 HTTP/1.1" 200 770783
2024-10-28 22:41:51 DEBUG Starting new HTTPS connection (1): assets.msn.com:443
2024-10-28 22:41:51 DEBUG https://assets.msn.com:443 "GET /resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.130&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20 HTTP/1.1" 200 770783
2024-10-28 22:41:51 DEBUG Starting new HTTPS connection (1): assets.msn.com:443
2024-10-28 22:41:51 DEBUG https://assets.msn.com:443 "GET /resolver/api/resolve/v3/config/?expType=AppConfig&expInstance=default&apptype=finance&v=20240430.130&targetScope=%7B%22audienceMode%22:%22adult%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22browser%22:%7B%22browserType%22:%22chrome%22,%22version%22:%220%22,%22ismobile%22:%22false%22%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22deviceFormFactor%22:%22desktop%22,%22domain%22:%22www.msn.com%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22locale%22:%7B%22content%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D,%22display%22:%7B%22language%22:%22vi%22,%22market%22:%22vn%22%7D%7D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22ocid%22:%22hpmsn%22,%22os%22:%22macos%22,%22platform%22:%22web%22,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22pageType%22:%22financestockdetails%22%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20 HTTP/1.1" 200 770783
ERROR: test_msncomponents_init_valid_source (tests.common.test_data_explorer.TestMSNComponents)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 472, in _decode
    data = self._decoder.decompress(data)
brotli.error: BrotliDecoderDecompressStream failed while processing the stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 1040, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 1188, in read_chunked
    decoded = self._decode(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 476, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/tests/common/test_data_explorer.py", line 184, in test_msncomponents_init_valid_source
    msn = MSNComponents(symbol="EURUSD", source="MSN")
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 458, in __init__
    self._initialize_components()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 462, in _initialize_components
    self.quote = Quote(self.symbol, self.source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 84, in __init__
    self.data_source = self._load_data_source()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 92, in _load_data_source
    return module.Quote(self.symbol.lower())
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/quote.py", line 28, in __init__
    self.apikey = msn_apikey(headers=self.headers, version=api_version)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/helper.py", line 32, in msn_apikey
    response = requests.request("GET", url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 824, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

ERROR: test_msncomponents_update_symbol (tests.common.test_data_explorer.TestMSNComponents)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 472, in _decode
    data = self._decoder.decompress(data)
brotli.error: BrotliDecoderDecompressStream failed while processing the stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 956, in read
    decoded_data = self._decode(data, decode_content, flush_decoder)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 476, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/tests/common/test_data_explorer.py", line 192, in test_msncomponents_update_symbol
    msn = MSNComponents(symbol="EURUSD", source="MSN")
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 458, in __init__
    self._initialize_components()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 462, in _initialize_components
    self.quote = Quote(self.symbol, self.source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 84, in __init__
    self.data_source = self._load_data_source()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 92, in _load_data_source
    return module.Quote(self.symbol.lower())
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/quote.py", line 28, in __init__
    self.apikey = msn_apikey(headers=self.headers, version=api_version)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/helper.py", line 32, in msn_apikey
    response = requests.request("GET", url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 824, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

ERROR: test_vnstock_crypto (tests.common.test_data_explorer.TestVnstock)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 472, in _decode
    data = self._decoder.decompress(data)
brotli.error: BrotliDecoderDecompressStream failed while processing the stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 956, in read
    decoded_data = self._decode(data, decode_content, flush_decoder)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 476, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/tests/common/test_data_explorer.py", line 33, in test_vnstock_crypto
    crypto = vnstock.crypto(symbol="BTC")
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/vnstock.py", line 55, in crypto
    return MSNComponents(self.symbol, source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 458, in __init__
    self._initialize_components()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 462, in _initialize_components
    self.quote = Quote(self.symbol, self.source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 84, in __init__
    self.data_source = self._load_data_source()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 92, in _load_data_source
    return module.Quote(self.symbol.lower())
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/quote.py", line 28, in __init__
    self.apikey = msn_apikey(headers=self.headers, version=api_version)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/helper.py", line 32, in msn_apikey
    response = requests.request("GET", url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 824, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

ERROR: test_vnstock_fx (tests.common.test_data_explorer.TestVnstock)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 472, in _decode
    data = self._decoder.decompress(data)
brotli.error: BrotliDecoderDecompressStream failed while processing the stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 956, in read
    decoded_data = self._decode(data, decode_content, flush_decoder)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 476, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/tests/common/test_data_explorer.py", line 27, in test_vnstock_fx
    fx = vnstock.fx(symbol="EURUSD")
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/vnstock.py", line 50, in fx
    return MSNComponents(self.symbol, source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 458, in __init__
    self._initialize_components()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 462, in _initialize_components
    self.quote = Quote(self.symbol, self.source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 84, in __init__
    self.data_source = self._load_data_source()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 92, in _load_data_source
    return module.Quote(self.symbol.lower())
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/quote.py", line 28, in __init__
    self.apikey = msn_apikey(headers=self.headers, version=api_version)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/helper.py", line 32, in msn_apikey
    response = requests.request("GET", url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 824, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

ERROR: test_vnstock_stock (tests.common.test_data_explorer.TestVnstock)
Traceback (most recent call last):
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/tests/common/test_data_explorer.py", line 21, in test_vnstock_stock
    stock = vnstock.stock(symbol="ACB")
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/vnstock.py", line 45, in stock
    return StockComponents(self.symbol, source, show_log=self.show_log)
AttributeError: 'Vnstock' object has no attribute 'symbol'

ERROR: test_vnstock_world_index (tests.common.test_data_explorer.TestVnstock)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 472, in _decode
    data = self._decoder.decompress(data)
brotli.error: BrotliDecoderDecompressStream failed while processing the stream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 956, in read
    decoded_data = self._decode(data, decode_content, flush_decoder)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 476, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/tests/common/test_data_explorer.py", line 39, in test_vnstock_world_index
    world_index = vnstock.world_index(symbol="DJI")
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/vnstock.py", line 60, in world_index
    return MSNComponents(self.symbol, source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 458, in __init__
    self._initialize_components()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 462, in _initialize_components
    self.quote = Quote(self.symbol, self.source)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 84, in __init__
    self.data_source = self._load_data_source()
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/common/data/data_explorer.py", line 92, in _load_data_source
    return module.Quote(self.symbol.lower())
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/quote.py", line 28, in __init__
    self.apikey = msn_apikey(headers=self.headers, version=api_version)
  File "/Users/mrthinh/Library/CloudStorage/OneDrive-Personal/Github/vnstock/vnstock3/explorer/msn/helper.py", line 32, in msn_apikey
    response = requests.request("GET", url, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 824, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))

2024-10-28 22:41:51 INFO Test suite tests.common.test_data_explorer finished
